# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a224a5be16be3bf12c9020830a6467ba18641bc637aad5d9b47ee6e54a5a0a89246fe5718ad129b274b19a623b1821c1c2e7d3c0fac0d12ba9c91f985feb16ee

test:
  secret_key_base: 2b52ec3e5ca9dd38e86156db6cc2bec9ddc61d2067ab977e1a150211a102093d104a49168398734ede307c44aabf8b668ba56864ddce4398a23ba89d719b6b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
